config/routes.rb
Rails.application.routes.draw do
  get  "/about" => "about#index"
  get "/password" => "users#password_edit", as: :password_edit
  patch "/password" => "users#password_update", as: :password_update

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :posts do
    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]
  resources :password_resets
  root "home#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true, uniqueness: true
  belongs_to :post
  belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category
  belongs_to :user

  validates :title, presence: true, uniqueness: true, length: {minimum: 7}
  validates :body, presence: true

  def self.search(search)
    where("title ILIKE ? OR body ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def new_first_comments
    comments.order(created_at: :desc)
  end

  def favourited_by?(user)
    favourites.exists?(user: user)
  end

  def favourited_for(user)
    favourites.find_by_user_id user
  end

  # def self.truncate(truncate)
  #   if body.length > 100
  #     truncate(body, :length => 97)
  #
  #   end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :title, uniqueness: true, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :post


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  def full_name
    "#{first_name} #{last_name}"
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, except: [:show, :index]
    def new
      @comment = Comment.new
    end
    def create
      @comment = Comment.new comment_params
      @post = Post.find params[:post_id]
      @comment.user = current_user
      @comment.post = @post
      @comments = Comment.order(created_at: :desc)
      if @comment.save
        redirect_to post_path(@post)
      else
        render "/posts/show"
      end
    end

    def destroy
      post = Post.find params[:post_id]
      comment = Comment.find params[:id]
      comment.destroy
      redirect_to post_path(post)
    end

  end

private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def authenticate_user!
    redirect_to new_session_path, alert: "please sign in" unless session[:user_id].present?
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def index
    @posts = Post.search(params[:search]).order("created_at DESC").paginate(:per_page => 5, :page => params[:page])
  end

  def edit
  end

  def update
      if @post.update post_params
        redirect_to post_path(@post)
      else
        render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id, {tag_ids: []})
  end

  def find_post
    @post = Post.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Signed in"
      else
      render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You're now signed up!"
    else
      render :new
    end
  end

  def edit
  end

  def update
      if @user.update user_params
        redirect_to user_path(@user), notice: "update successful"
      else
        render :edit
      end
  end

  def password_edit
    @user = current_user
  end

  def password_update
    @user = current_user
      user_params= params.require(:user).permit(:new_password, :password, :password_confirmation)
    if @user.authenticate(user_params[:password]) && @user.authenticate(user_params[:new_password]) == false
       @user.update(password: user_params[:new_password], password_confirmation: user_params[:password_confirmation])
       redirect_to root_path, notice: "Password updated"
    else
      if @user.authenticate(user_params[:password]) == false
        flash[:alert] = "Incorrect Password"
      elsif @user.authenticate(user_params[:new_password])
        flash[:alert] = "The new password should be different from the old password"
      else
      render :password_edit
      end
    end
  end

private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def find_user
      @user = User.find params[:id]
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= @comment.errors.full_messages.join(", ") %>
<%= form_for @comment do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<%= link_to "Write a new comment", new_comment_path(@comment) %>
<h1>All Comments</h1>
<% @comments.each do |comment| %>
  <%= link_to comment.body.truncate(30), comment_path(comment) %>
  <hr>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= @comment.errors.full_messages.join(", ") %>
<%= form_for @comment do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<p><%= @comment.body %></p>
<%= link_to "Edit", edit_comment_path(@comment) %>
<%= link_to "Delete", comment_path(@comment),
                      method: :delete,
                      data:   {confirm: "Are you sure?"} %>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.association :category, include_blank: false %>
  <%= f.association :tags, as: :check_boxes %>
  <div class="actions"><%= submit_tag "Submit", class: "btn btn-danger btn-custom"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<%= form_tag(posts_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search" %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>

<%= link_to "Write a new post", new_post_path(@post) %>

<h1>All Posts</h1>
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
  <hr>
<% end %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>Submit a new post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="container">
<h1><%= @post.title.titleize %></h1>
<p>category: <%= @post.category.name %></p>
<p><%= @post.body %></p>
<p>Created By: <%= @post.user.full_name if @post.user %></p>
<p>Tags: <%= @post.tags.map {|t| t.title.capitalize}.join(", ")%></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post),
                      method: :delete,
                      data:   {confirm: "Are you sure?"} %>

  <% if @post.favourited_by?(current_user) %>
  <%= link_to "unfavourite",
              post_favourite_path(@post, @post.favourited_for(current_user)),
              method: :delete %>
  <% else %>
  <%= link_to "favourite", post_favourites_path(@post), method: :post %>
  <% end %>


<h2>Create a Comment</h2>
  <%= @comment.errors.full_messages.join(', ')%>
  <%= form_for [@post, @comment] do |f| %>
  <div>
  Comment
  <%= f.text_area :body %>
  </div>
  <%= f.submit %>
  <% end %>

<h2>Comments</h2>
  <% @post.new_first_comments.each do |com| %>
  <%= com.user.full_name if com.user %>
  |
  <%= com.body %>
  <%= link_to "Delete", post_comment_path(@post, com),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
<hr>
<% end %>
</div>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name, :label => "First Name" %>
  <%= f.input :last_name, :label => "Last Name" %>
  <%= f.input :email, :label => "Email" %>
  <hr>
  <div class="actions"><%= submit_tag "Submit", class: "btn btn-danger btn-custom"%>
  </div>
<% end %>

app/views/users/new.html.erb
<h1> Create an Account </h1>
<div class="container">
  <%= @user.errors.full_messages.join(", ") %>
  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name, :label => "First Name" %>
    <%= f.input :last_name, :label => "Last Name" %>
    <%= f.input :email, :label => "Email" %>
    <%= f.input :password, :label => "Password", required: true %>
    <%= f.input :password_confirmation, :label => "Password Confirmation", required: true %>
    <hr>
    <div class="actions"><%= submit_tag "Submit", class: "btn btn-danger btn-custom"%>
    </div>
  <% end %>
</div>

app/views/users/password_edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :password, :label => "Old Password", required: true%>
  <%= f.input :new_password, :label => "New Password", required: true %>
  <%= f.input :password_confirmation, :label => "Password Confirmation", required: true %>
  <hr>
  <%= f.button :submit, class: "btn btn-default" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%=@user.last_name%></h1>
<p><%=@user.email %> </p>
<%= link_to "Edit Profile", edit_user_path(@user) %>